### ISSUE TITLE
Expose the subdirectories of a package

### ISSUE THREAD

**Issue by ekadas** [SendSafely/Java-Client-API#14]
Hey,

I would like to add files to an existing sub-directory of a workspace package, for which I need to know the ID of the directory. I can see that this information is exposed as part of the [REST API](https://bump.sh/doc/sendsafely-rest-api#operation-get-package-parameter), however the Java Client does not expose the list of directories for a Package.

Could you please add sub directories to the Package class?

Thank you!

**Comment by SendSafely-GitHub** [comment]
Hi Endre --

Thanks for your feedback. Take a look at the [getDirectory](https://github.com/SendSafely/Java-Client-API/blob/v3.1.5/SendSafelyAPI/src/com/sendsafely/SendSafely.java#L878) method, which might be what you need. 

It returns a [Directory](https://github.com/SendSafely/Java-Client-API/blob/v3.1.5/SendSafelyAPI/src/com/sendsafely/Directory.java#L9) object that includes a collection of [Subdirectory](https://github.com/SendSafely/Java-Client-API/blob/v3.1.5/SendSafelyAPI/src/com/sendsafely/dto/Subdirectory.java) items that can be read using [getSubDirectories](https://github.com/SendSafely/Java-Client-API/blob/v3.1.5/SendSafelyAPI/src/com/sendsafely/Directory.java#L73). Each Subdirectory has a [directoryId](https://github.com/SendSafely/Java-Client-API/blob/v3.1.5/SendSafelyAPI/src/com/sendsafely/dto/Subdirectory.java#L23) that you can read in order to fetch its contents or upload files to it.

You can enumerate the entire folder structure of a workspace by using [getDirectory](https://github.com/SendSafely/Java-Client-API/blob/v3.1.5/SendSafelyAPI/src/com/sendsafely/SendSafely.java#L878) starting at the root directory (use [getRootDirectoryId](https://github.com/SendSafely/Java-Client-API/blob/v3.1.5/SendSafelyAPI/src/com/sendsafely/BasePackage.java#L208) to get the ID of the root) and then traversing down into each subdirectory by calling [getDirectory](https://github.com/SendSafely/Java-Client-API/blob/v3.1.5/SendSafelyAPI/src/com/sendsafely/SendSafely.java#L878) on each one.

Let us know if that gets you the information you need for your use case. 

Thanks!
